**Numpy (Numerical Python)**
Numpy is a powerful library for numerical computations in Python. It provides support for arrays, matrices, and mathematical operations.

In [1]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# Creating a 2D array
arr2 = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr2)

# Creating arrays with zeros and ones
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
print("Zeros Array:\n", zeros)
print("Ones Array:\n", ones)


1D Array: [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape:", arr.shape)  # Dimensions of the array
print("Size:", arr.size)    # Total number of elements
print("Data Type:", arr.dtype)  # Data type of elements

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)

# Universal functions
print("Square Root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Square Root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at [1,2]:", arr[1, 2])  # Accessing single element
print("First row:", arr[0])           # First row
print("Second column:", arr[:, 1])    # All rows, second column

Element at [1,2]: 6
First row: [1 2 3]
Second column: [2 5 8]


In [5]:
# Random numbers
rand_arr = np.random.rand(3, 3)  # Uniform distribution
print("Random Array:\n", rand_arr)

# Random integers
rand_ints = np.random.randint(0, 10, size=(3, 3))
print("Random Integers:\n", rand_ints)


Random Array:
 [[0.67065771 0.92356698 0.93547211]
 [0.17935364 0.24559896 0.13782782]
 [0.4939099  0.16669618 0.2720132 ]]
Random Integers:
 [[5 9 3]
 [3 4 0]
 [5 0 6]]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # Reshaping into 2x3 matrix
print("Reshaped Array:\n", reshaped)

# Transposing a matrix
transposed = reshaped.T
print("Transposed Array:\n", transposed)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


**Pandas**

Pandas is a library for data manipulation and analysis, built on top of Numpy.

In [9]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Salary": [50000, 60000, 70000]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)


DataFrame:
       Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000


In [ ]:
# Reading data from a CSV file
df = pd.read_csv("sample.csv")
print("First 5 Rows:\n", df.head())

# Saving a DataFrame to a CSV file
df.to_csv("output.csv", index=False)

In [10]:
print("Columns:", df.columns)
print("Data Types:\n", df.dtypes)
print("Shape:", df.shape)
print("Summary:\n", df.describe())  # Statistics for numeric columns

Columns: Index(['Name', 'Age', 'Salary'], dtype='object')
Data Types:
 Name      object
Age        int64
Salary     int64
dtype: object
Shape: (3, 3)
Summary:
         Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0


In [11]:
# Selecting a column
print("Age Column:\n", df["Age"])

# Selecting rows
print("First Row:\n", df.iloc[0])
print("Rows where Age > 30:\n", df[df["Age"] > 30])


Age Column:
 0    25
1    30
2    35
Name: Age, dtype: int64
First Row:
 Name      Alice
Age          25
Salary    50000
Name: 0, dtype: object
Rows where Age > 30:
       Name  Age  Salary
2  Charlie   35   70000


In [12]:
# Creating a DataFrame with missing values
data = {"A": [1, 2, None], "B": [None, 3, 4]}
df = pd.DataFrame(data)
print("Original Data:\n", df)

# Handling missing values
df_filled = df.fillna(0)  # Replace NaN with 0
print("Filled Data:\n", df_filled)

df_dropped = df.dropna()  # Drop rows with NaN
print("Dropped Rows:\n", df_dropped)

Original Data:
      A    B
0  1.0  NaN
1  2.0  3.0
2  NaN  4.0
Filled Data:
      A    B
0  1.0  0.0
1  2.0  3.0
2  0.0  4.0
Dropped Rows:
      A    B
1  2.0  3.0


In [15]:
df.head()

A    B
0  1.0  NaN
1  2.0  3.0
2  NaN  4.0

In [18]:
# Adding a new column
df["Bonus"] = df["A"] * 0.1
print("After Adding Column:\n", df)

# Dropping a column
df = df.drop("Bonus", axis=1)
print("After Dropping Column:\n", df)

After Adding Column:
      A    B  Bonus
0  1.0  NaN    0.1
1  2.0  3.0    0.2
2  NaN  4.0    NaN
After Dropping Column:
      A    B
0  1.0  NaN
1  2.0  3.0
2  NaN  4.0


In [20]:
# Grouping by a column
grouped = df.groupby("A").mean()
print("Grouped Data:\n", grouped)

Grouped Data:
        B
A       
1.0  NaN
2.0  3.0


In [21]:
data1 = {"ID": [1, 2], "Name": ["Alice", "Bob"]}
data2 = {"ID": [1, 2], "Salary": [50000, 60000]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

merged = pd.merge(df1, df2, on="ID")
print("Merged Data:\n", merged)


Merged Data:
    ID   Name  Salary
0   1  Alice   50000
1   2    Bob   60000
